# Generated by Django 4.1.4 on 2023-02-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='Товар')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('upgrade_price', models.IntegerField(default=0, verbose_name='Цена улучшения')),
                ('rp_price', models.IntegerField(default=0, verbose_name='Цена в РП')),
                ('rp_upgrade_price', models.IntegerField(default=0, verbose_name='Цена улучшения в РП')),
                ('item_level', models.IntegerField(default=0, verbose_name='Уровень предмета')),
                ('image', models.ImageField(upload_to='images/product/', verbose_name='Фото')),
                ('can_upgrade', models.BooleanField(default=False, verbose_name='Улучшаемый')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категория товаров',
            },
        ),
        migrations.CreateModel(
            name='ShopHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamID', models.IntegerField(verbose_name='Пользователь')),
                ('coins', models.IntegerField(default=0, verbose_name='Монет')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamID', models.IntegerField(verbose_name='Пользователь')),
                ('coins', models.IntegerField(default=0, verbose_name='Монет')),
                ('rp', models.IntegerField(default=0, verbose_name='РП')),
                ('total_coins', models.IntegerField(default=0, verbose_name='Суммарный донат')),
                ('ban_status', models.BooleanField(default=False, verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед')),
                ('lose', models.IntegerField(default=0, verbose_name='Поражений')),
                ('games', models.IntegerField(default=0, verbose_name='Игр')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('player_exp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('skill_points', models.IntegerField(default=0, verbose_name='Поинтов')),
                ('str', models.IntegerField(default=0, verbose_name='Сила')),
                ('agi', models.IntegerField(default=0, verbose_name='Ловкость')),
                ('int', models.IntegerField(default=0, verbose_name='Итлеллект')),
                ('hpr', models.IntegerField(default=0, verbose_name='Реген ХП')),
                ('mpr', models.IntegerField(default=0, verbose_name='Реген МП')),
                ('movespeed', models.IntegerField(default=0, verbose_name='Скорость передвижения')),
                ('armor', models.IntegerField(default=0, verbose_name='Броня')),
                ('mresist', models.IntegerField(default=0, verbose_name='Резист магии')),
                ('exp', models.IntegerField(default=0, verbose_name='Опыт за крипа')),
                ('coolddown', models.IntegerField(default=0, verbose_name='Перезарядка')),
                ('damage', models.IntegerField(default=0, verbose_name='Урон')),
                ('attack_speed', models.IntegerField(default=0, verbose_name='Скорость атаки')),
                ('evasion', models.IntegerField(default=0, verbose_name='Уклонение')),
                ('spellamp', models.IntegerField(default=0, verbose_name='Усиление закленаний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='back.user', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('active', models.BooleanField(default=False, verbose_name='Активность')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.product', verbose_name='Предмет')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='back.user', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.productcategory', verbose_name='Категория'),
        ),
    ]
