# Generated by Django 4.1.4 on 2023-02-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_level',
            field=models.IntegerField(default=1, verbose_name='Уровень предмета'),
        ),
    ]
