# Generated by Django 4.1.4 on 2023-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_level',
        ),
        migrations.AlterField(
            model_name='useritems',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Уровень/Кол-во'),
        ),
    ]
