# Generated by Django 4.1.4 on 2023-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_remove_product_item_level_alter_useritems_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='steamID',
            field=models.BigIntegerField(verbose_name='Пользователь'),
        ),
    ]
