# Generated by Django 4.1.4 on 2023-03-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_user_steamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins',
        ),
    ]
