# Generated by Django 4.1.4 on 2023-03-13 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_remove_userprofile_lose_remove_userprofile_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='shophistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.product', verbose_name='Предмет'),
        ),
    ]
