# Generated by Django 4.1.4 on 2023-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_shophistory_date_shophistory_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shophistory',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='steamID',
            field=models.BigIntegerField(verbose_name='Пользователь'),
        ),
    ]
