# Generated by Django 4.1.4 on 2023-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_shophistory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophistory',
            name='item',
            field=models.CharField(default=None, max_length=64, verbose_name='Предмет'),
        ),
    ]
