# Generated by Django 4.1.4 on 2023-03-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_shophistory_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='coolddown',
            new_name='cooldown',
        ),
    ]
