# Generated by Django 4.1.4 on 2023-03-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_rename_coolddown_userprofile_cooldown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='games',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('games', models.IntegerField(default=0, verbose_name='Игр')),
                ('win_games', models.IntegerField(default=0, verbose_name='Побед')),
                ('simple_game', models.IntegerField(default=0, verbose_name='Обычный мод')),
                ('ability_game', models.IntegerField(default=0, verbose_name='Абилити мод')),
                ('damage_deal', models.BigIntegerField(verbose_name='Нанес урон')),
                ('damage_take', models.BigIntegerField(verbose_name='Получил урон')),
                ('creeps', models.BigIntegerField(verbose_name='Крипов')),
                ('bosses', models.BigIntegerField(verbose_name='Боссов')),
                ('golden_creeps', models.BigIntegerField(verbose_name='Золотых крипов')),
                ('runes', models.BigIntegerField(verbose_name='Рун')),
                ('min_time', models.BigIntegerField(verbose_name='Минут в игре')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.user', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
