# Generated by Django 4.1.4 on 2023-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_remove_userprofile_games_remove_userprofile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='bosses',
            field=models.BigIntegerField(default=0, verbose_name='Боссов'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='creeps',
            field=models.BigIntegerField(default=0, verbose_name='Крипов'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='damage_deal',
            field=models.BigIntegerField(default=0, verbose_name='Нанес урон'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='damage_take',
            field=models.BigIntegerField(default=0, verbose_name='Получил урон'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='golden_creeps',
            field=models.BigIntegerField(default=0, verbose_name='Золотых крипов'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='min_time',
            field=models.BigIntegerField(default=0, verbose_name='Минут в игре'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='runes',
            field=models.BigIntegerField(default=0, verbose_name='Рун'),
        ),
    ]
