# Generated by Django 4.1.4 on 2023-03-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_alter_userstatistic_bosses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.user', verbose_name='Статистика'),
        ),
    ]
