# Generated by Django 4.1.4 on 2023-03-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_alter_userstatistic_options_alter_userstatistic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='back.user', verbose_name='Статистика'),
        ),
    ]
