# Generated by Django 4.1.4 on 2023-03-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_alter_userstatistic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistic',
            name='runes',
        ),
    ]
