# Generated by Django 4.1.4 on 2023-03-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_userprofile_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.IntegerField(verbose_name='Время игры')),
                ('game_difficulty', models.IntegerField(verbose_name='Номер сложности')),
            ],
            options={
                'verbose_name': 'История игр',
                'verbose_name_plural': 'История игр',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField(verbose_name='Пользователь')),
                ('player_level', models.IntegerField(verbose_name='Уровень аккаунта игрока')),
                ('hero', models.CharField(max_length=50)),
                ('item1', models.CharField(max_length=50)),
                ('item2', models.CharField(max_length=50)),
                ('item3', models.CharField(max_length=50)),
                ('item4', models.CharField(max_length=50)),
                ('item5', models.CharField(max_length=50)),
                ('item6', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.gamehistory')),
            ],
        ),
    ]
