# Generated by Django 4.1.4 on 2023-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_gamehistory_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shophistory',
            options={'verbose_name': 'История покупок', 'verbose_name_plural': 'История покупок'},
        ),
        migrations.AlterField(
            model_name='player',
            name='hero',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='item6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
