# Generated by Django 4.1.4 on 2023-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_alter_shophistory_options_alter_player_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг аккаунта игрока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='hero',
            field=models.CharField(max_length=50, null=True, verbose_name='Герой'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item1',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item2',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item3',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 4'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item4',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 5'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item5',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 6'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item6',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 7'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
    ]
