# Generated by Django 4.1.4 on 2023-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_player_player_rating_alter_player_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_rp',
            field=models.IntegerField(default=0, verbose_name='Тотал РП'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item1',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item2',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item3',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item4',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 4'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item5',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 5'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item6',
            field=models.CharField(max_length=50, null=True, verbose_name='Предмет 6'),
        ),
    ]
