# Generated by Django 4.1.4 on 2023-03-30 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_user_total_rp_alter_player_item1_alter_player_item2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 30, 17, 52, 47, 682288, tzinfo=datetime.timezone.utc)),
        ),
    ]
