# Generated by Django 4.1.4 on 2023-06-01 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_alter_shophistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_hero',
            field=models.BooleanField(default=False, verbose_name='Анаким'),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 1, 5, 38, 9, 222965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='int',
            field=models.IntegerField(default=0, verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spellamp',
            field=models.IntegerField(default=0, verbose_name='Усиление заклинаний'),
        ),
    ]
